### PR TITLE
new build in order for wrapperStyles and wrapperProps to work as expected

### PR DESCRIPTION
**Pull request by hontas**
Resolves the hard coded `display: inline-block` that is in the current build.
And let's us set wrapperStyle and wrapperProps like in examples and in the source.

### CODE REVIEW

**Comment by robcalcroft** [comment]
Looks good, might want to consider amending the commit message to be more descriptive?

**Comment by hontas** [comment]
like why it's a new build? is that what you mean @robcalcroft?

**Comment by robcalcroft** [comment]
@hontas I meant more of a description of the PR itself, if I were to do a `git log` and see `new build`, I'd have little idea of what changes that commit made. Eg `Resolves the hard coded display: inline-block` would be more descriptive.

**Comment by hontas** [comment]
@robcalcroft fair point ;) is this ok?

**Comment by robcalcroft** [comment]
Yeh that works a lot better 👍

**Comment by hontas** [comment]
resolves #66

**Comment by rich-b** [comment]
👍

**Comment by hontas** [comment]
@robcalcroft any plans on merging and publishing a patch to npm?

**Comment by robcalcroft** [comment]
@hontas I'm not a contributer on this project sorry

**Comment by hontas** [comment]
@ryanflorence any planson merging this PR and publishing a patch to npm? Without it wrapperStyle and wrapperProps is broken..

**Pull request closed without merging**
