### PR TITLE
Deprecate string ref

### PR DESCRIPTION
**Pull request by teameh**
Rebased and cleaned up version of https://github.com/reactjs/react-autocomplete/pull/173 

LGTM!

@alvinsj I hope you're alright with me cleaning up your commit.

### CODE REVIEW

**Comment by CMTegner** [comment]
Contradictory to what I wrote in #173, I don't think we can actually land this in 1.0. I know of several production apps that would break if we rename the (undocumented) refs. Currently refs are the only way of accessing the imperative API of the inner `<input>`.

I have [some ideas](https://github.com/reactjs/react-autocomplete/commit/6c44944f485af163906fc3aebe1f904858956364) on how to solve this for 2.0.

**Comment by tiemevanveen** [comment]
>  I don't think we can actually land this in 1.0. I know of several production apps that would break if we rename the (undocumented) refs. 

Haha okay.. But then you can't make any breaking changes in 1.0?

> Currently refs are the only way of accessing the imperative API of the inner <input>.

Shouldn't that be included in v1.0 as well then?

**Comment by tiemevanveen** [comment]
> I have some ideas on how to solve this for 2.0.

Ah read to fast, okay, yeah that might make sense, you could also skip v1.0 altogether.

**Comment by CMTegner** [comment]
Fixed in f915315bfd89b6ab77b2125192b621cde609d1dc. We're still using the `this.refs` namespace for backwards compatibility.

**Pull request closed without merging**
