### PR TITLE
add .travis.yml, shields.io badge to README

### PR DESCRIPTION
**Pull request by sprjr**
Should close out #142, I added the travis hooks as well and will tune that based on the build status (ideally this would be passing / stable at the time of merge ;))

### CODE REVIEW

**Comment by sprjr** [comment]
```
$ npm test
> react-autocomplete@1.0.1 test /home/travis/build/reactjs/react-autocomplete
> jest
Using Jest CLI v13.2.3, jasmine2, babel-jest
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-autocomplete
  Paths: /home/travis/build/reactjs/react-autocomplete/package.json collides with /home/travis/build/reactjs/react-autocomplete/build/package.json
This warning is caused by a @providesModule declaration with the same name across two different files.
NO TESTS FOUND. 16 files checked.
  testPathDirs: /home/travis/build/reactjs/react-autocomplete - 16 matches
  testRegex: __tests__/.*.js$ - 2 matches
  testPathIgnorePatterns: build - 0 matches
The command "npm test" exited with 0.
Done. Your build exited with 0.
```

Looks like it'll need some tweaking.

**Comment by CMTegner** [comment]
That is very strange. I get the same haste-map warning, but the tests are found and run successfully. I've pushed 2b17f18db47e0c130e9f2043b103a047eaf4ba88 which hopefully fixes this problem.

**Comment by sprjr** [comment]
That seems to have done it from the logs:

```
9.95s$ npm test
> react-autocomplete@1.0.1 test /home/travis/build/reactjs/react-autocomplete
> jest
Using Jest CLI v13.2.3, jasmine2, babel-jest
 PASS  lib/__tests__/Autocomplete-test.js (6.739s)
20 tests passed (20 total in 1 test suite, run time 7.585s)
The command "npm test" exited with 0.
Done. Your build exited with 0.
```

One thing I noticed, running `npm test` locally for me I get a SyntaxError, it's failing on the `<Autocomplete` which I assume means it's a transpile error. I've got node 6 / npm 3 - but it didn't seem to work "out of the box." Missing documentation on something we need to do to run these now?

I also saw that in the travis config "4" and "stable" are effectively the same. I'm adding "6" and then we can merge this in and close #142.

**Comment by CMTegner** [comment]
>One thing I noticed, running npm test locally for me I get a SyntaxError, it's failing on the <Autocomplete which I assume means it's a transpile error. I've got node 6 / npm 3 - but it didn't seem to work "out of the box." Missing documentation on something we need to do to run these now?

Perhaps you have a `.babelrc` in your home dir that's somehow overriding the one in this repo? You shouldn't have to have any globally installed npm module or any sort of local setup to build/test.

**Comment by sprjr** [comment]
@CMTegner - interesting, so I saw `.babel.json` on home but no rogue `.babelrc`s that I could find. I looked at the Jest documentation, and even tried using `jest-cli, babel-jest, babel-polyfill` as instructed (as well as updated those deps). Still getting the error:

```
 react-autocomplete@1.0.1 test /Users/stephenrivasjr/Development/react-autocomplete
> jest

Using Jest CLI v14.0.0, jasmine2, babel-jest
 FAIL  lib/__tests__/Autocomplete-test.js (0s)
● Runtime Error
  - SyntaxError: /Users/stephenrivasjr/Development/react-autocomplete/lib/__tests__/Autocomplete-test.js: Unexpected token (11:4)
       9 | function AutocompleteComponentJSX (extraProps) {
      10 |   return (
    > 11 |     <Autocomplete 
         |     ^
      12 |       labelText="Choose a state from the US"
      13 |       inputProps={{name: "US state"}}
      14 |       getItemValue={(item) => item.name}
        at Parser.pp.raise (node_modules/babylon/lib/parser/location.js:22:13)
        at Parser.pp.unexpected (node_modules/babylon/lib/parser/util.js:89:8)
        at Parser.pp.parseExprAtom (node_modules/babylon/lib/parser/expression.js:522:12)
        at Parser.pp.parseExprSubscripts (node_modules/babylon/lib/parser/expression.js:277:19)
        at Parser.pp.parseMaybeUnary (node_modules/babylon/lib/parser/expression.js:257:19)
        at Parser.pp.parseExprOps (node_modules/babylon/lib/parser/expression.js:188:19)
        at Parser.pp.parseMaybeConditional (node_modules/babylon/lib/parser/expression.js:165:19)
        at Parser.pp.parseMaybeAssign (node_modules/babylon/lib/parser/expression.js:128:19)
        at Parser.pp.parseParenAndDistinguishExpression (node_modules/babylon/lib/parser/expression.js:596:26)
        at Parser.pp.parseExprAtom (node_modules/babylon/lib/parser/expression.js:481:19)
1 test suite failed, 0 tests passed (0 total in 1 test suite, run time 1.075s)
npm ERR! Test failed.  See above for more details.
```

I would _assume_ that Jest does not need anything in our local `.rc` files to support JSX - thus far I've not been able to just "get them running". Any other things I might be missing?

**Comment by CMTegner** [comment]
Very strange. 

> Using Jest CLI v14.0.0, jasmine2, babel-jest

Not sure how you're on v14, did you bump it manually? Perhaps you should try a fresh clone and see if the problem persists. The fact that it builds and tests on travis makes me think that there's something fishy going on with your local instance.

Here's my local info if you want to compare against yours:

```sh
christian on dante in ~/git/react-autocomplete on master*
› npm ls --depth=0
react-autocomplete@1.0.1 /Users/christian/git/react-autocomplete
├── babel-cli@6.11.4
├── babel-eslint@6.1.2
├── babel-jest@13.2.2
├── babel-preset-es2015@6.9.0
├── babel-preset-react@6.11.1
├── babel-preset-stage-0@6.5.0
├── dom-scroll-into-view@1.0.1
├── enzyme@2.4.1
├── eslint@2.13.1
├── eslint-config-rackt@1.1.1
├── jest@13.2.3
├── rackt-cli@0.6.1
├── react@0.14.8
├── react-addons-test-utils@0.14.8
└── react-dom@0.14.8

npm ERR! peer dep missing: karma@>=0.9, required by karma-ie-launcher@0.2.0
npm ERR! peer dep missing: karma@>=0.9, required by karma-phantomjs-launcher@1.0.1
npm ERR! peer dep missing: karma@>=0.9, required by karma-safari-launcher@0.1.1
christian on dante in ~/git/react-autocomplete on master*
› npm ls -g --depth=0
/Users/christian/.nvm/versions/node/v6.0.0/lib
├── generator-react-native-ignite@1.0.2
├── npm@3.8.6
├── rackt-cli@0.6.1
├── react-native-cli@1.0.0
├── react-native-ignite@1.0.2
├── rnpm@1.9.0
└── yo@1.8.4

christian on dante in ~/git/react-autocomplete on master*
› npm test
christian on dante in ~/git/react-autocomplete on master*
› cat .babelrc
{
  "env": {
    "test": {
      "presets": ["es2015", "stage-0", "react"]
    }
  }
}
christian on dante in ~/git/react-autocomplete on master*
› ls -la ~ | grep babel
christian on dante in ~/git/react-autocomplete on master*
› npm test

> react-autocomplete@1.0.1 test /Users/christian/git/react-autocomplete
> jest

Using Jest CLI v13.2.3, jasmine2, babel-jest
 PASS  lib/__tests__/Autocomplete-test.js (1.155s)
20 tests passed (20 total in 1 test suite, run time 1.912s)
christian on dante in ~/git/react-autocomplete on master*
› node --version && npm --version
v6.0.0
3.8.6
```

**Comment by sprjr** [comment]
@CMTegner Interestingly, the fresh clone / install didn't do the trick.

- [x] my local `npm ls` matches yours
- [ ] my npm version matches yours (diff: npm@3.10.3, same occured using my 2.x shell)
- [ ] my global `npm ls` matches yours (diff: npm@3 has nothing here (using nave), npm@2 diff below)
- [x] my `cat .babelrc` matches yours
- [ ] my `ls ~ | grep babel` matches yours (diff: I have a `.babel.json` that appears here, but removing it doesn't seem to improve anything)
- [ ] my `npm test` matches yours (diff above, and yes the versions were bumped by me in an attempt to see if that resolved - but are identical on fresh install)

`npm@2.x ls -g --depth=0`
```
> npm ls -g --depth=0
/usr/local/liba
├── create-react-app@0.1.0
├── generator-bh-module@2.8.1
├── gulp@4.0.0-alpha.1 (git://github.com/gulpjs/gulp.git#aaed69d1fd73750227e803035b2a75d0f49e7de0)
├── nave@0.5.3
├── now@0.19.0
├── now-serve@0.3.1
├── npm@2.15.5
├── npmrc@1.1.1
├── pm2@1.1.3
├── rackt-cli@0.6.1
├── selenium-server@2.53.0
├── selenium-standalone@5.1.0
└── yo@1.6.0
```

So, something I have going on locally is for sure causing this. I'm hesitant to say its the npm version, or the global npm installs - although if it was I'd wonder if the global gulp is part of the issue before anything else (just because its more commonly used?).

I'll keep digging in to see what could possibly cause this, but it seems like `jest` on my machine just will not transpile the JSX properly before starting the suite. Something I've overlooked I'm sure but I'm otherwise unable to run the tests for now :/

**Comment by sprjr** [comment]
@CMTegner well, something new this morning. (Sorry if this is pestering you btw ;))

http://stackoverflow.com/questions/33662225/react-jest-example-doesnt-work - same thing I'm seeing, more or less. The issue linked is 404 though, however `npm i babel-jest@^5.3.0` produces _this_ output instead (tailed just the end of it):

```
● Autocomplete click event handlers › it should update input value from selected menu item and close the menu
  - Error: This method is only meant to be run on single node. 0 found instead.
        at ReactWrapper.single (node_modules/enzyme/build/ReactWrapper.js:1319:17)
        at ReactWrapper.simulate (node_modules/enzyme/build/ReactWrapper.js:711:14)
        at Object.eval (lib/__tests__/Autocomplete-test.js:270:30)
        at Object.<anonymous> (node_modules/jest-jasmine2/build/jasmine-pit.js:40:32)
        at callback [as _onTimeout] (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:477:19)
        at Timer.listOnTimeout (timers.js:92:15)
● Autocomplete#renderMenu › it should return a <div ref="menu"> ReactComponent when renderMenu() is called
  - TypeError: Cannot read property 'type' of undefined
        at Object.eval (lib/__tests__/Autocomplete-test.js:292:28)
        at Object.<anonymous> (node_modules/jest-jasmine2/build/jasmine-pit.js:40:32)
        at callback [as _onTimeout] (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:477:19)
        at Timer.listOnTimeout (timers.js:92:15)
● Autocomplete#renderMenu › it should return a menu ReactComponent with a subset of children when partial match text has been entered
  - TypeError: Cannot read property 'props' of undefined
        at Object.eval (lib/__tests__/Autocomplete-test.js:302:28)
        at Object.<anonymous> (node_modules/jest-jasmine2/build/jasmine-pit.js:40:32)
        at callback [as _onTimeout] (node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/browser/Window.js:477:19)
        at Timer.listOnTimeout (timers.js:92:15)
● Autocomplete#renderMenu › it should allow using custom components
  - Expected 0 to be 1.
        at jasmine.buildExpectationResult (node_modules/jest-jasmine2/build/index.js:92:44)
        at Object.eval (lib/__tests__/Autocomplete-test.js:326:39)
        at Object.<anonymous> (node_modules/jest-jasmine2/build/jasmine-pit.js:40:32)
  - Expected 0 to be 50.
        at jasmine.buildExpectationResult (node_modules/jest-jasmine2/build/index.js:92:44)
        at Object.eval (lib/__tests__/Autocomplete-test.js:327:39)
        at Object.<anonymous> (node_modules/jest-jasmine2/build/jasmine-pit.js:40:32)
20 tests failed, 0 tests passed (20 total in 1 test suite, run time 2.024s)
```

So it seems that got me over the hump on the Syntax error, and in to a land of broken tests - which are passing on other machines on master. O_o

**Comment by CMTegner** [comment]
A couple of more things to try:
* `npm cache clear` (then install again)
* `./node_modules/.bin/jest --no-cache`

The fact that transpilation was a success after downgrading to `babel-jest` makes me think that babel may be struggling to read `.babelrc`. Try adding some bogus presets to `.babelrc` and see if babel starts complaining.

Also, try unwrapping "presets" so you're left with this:

```json
{
  "presets": ["es2015", "stage-0", "react"]
}
```

What OS are you on btw?

**Comment by sprjr** [comment]
Aha! I'd already tried the cache clear. The other command you suggested also yielded the same results. I _also_ tried breaking the `.babelrc`, and I tried swapping the order to have react at the front. All of them the same.

Hoisting presets up to the top level worked though. My `env | grep NODE` is `NODE_ENV=development` - where is that env.test set / read from normally? The tests run and pass as long as I do not have presets down in there. Not sure why that would impact it on my env, but not on yours/travisci...

I'm on Mac OSX.

**Comment by CMTegner** [comment]
The default is to have "presets" and friends at the top level, but you can scope properties in "env"s if you need to vary the babel config between environments. I'm not 100% sure why it's currently scoped, or where the "test" env comes from (maybe jest sets it?). All I know is that it was added with the initial batch of tests, and that it's not needed in our current setup.

**Comment by CMTegner** [comment]
I don't have any NODE_ENV set in env, and I'm guessing travis doesn't either, but playing around with NODE_ENV locally I still couldn't reproduce the issue. I think that's probably the closest to an explanation we've come yet, but I'm still not satisfied :0

**Pull request merged**
