### PR TITLE
[added] wrapperProps and wrapperStyle props

### PR DESCRIPTION
**Pull request by zoeabryant**
Thank you for this contribution, it has been very useful in our project.
I have created this pull request because we needed more control over the rendering of the widget. Our project has a very strict design manual, so it is important that we are able to add classes and overwrite default styling.

### CODE REVIEW

**Comment by cdevienne** [comment]
I used your patch for our application. +1 for an upstream merge !

Thanks

**Comment by otmjka** [comment]
+1

**Comment by docentq2** [comment]
+1

**Comment by pyrotechnick** [comment]
+1 and a "thank you" to @zoeabryant. This is absolutely vital.

**Comment by joe-harter** [comment]
What is delaying the merge of this? Is there anything I can do to help speed it along?

**Comment by Neitsch** [comment]
+1
@ryanflorence @sprjr is this project still active?

**Comment by sprjr** [comment]
Moderately active. Ryan asked to review "API changes" but otherwise I'm trying to catch up on some of these PRs and get it moving again as one of our internal modules uses it too

I'm going to merge #77 tomorrow (huzzah, tests) and then try to get the other PR with recent comments merged as well. I can look at a few more later this week likely as well.

**Comment by orbiteleven** [comment]
@sprjr @zoeabryant Can we get this in?

**Comment by sprjr** [comment]
This will need rebased from the latest merge from master, and we should include tests that verify the `wrapperProps` and `wrapperStyle` make it in as intended. Other than that it looks good to me.

**Comment by laughnan** [comment]
what is the status of this PR?

**Comment by Neitsch** [comment]
Should be closed. Resolved by #91

**Pull request closed without merging**
